removed github link for bots
hexlet-codebattle/codebattle pull request #1006
Opened 2021-04-23 10:54 UTC by Surtt

![github-icon](https://avatars0.githubusercontent.com/in/15368?s=40&amp;v=4) closes #789
Убрал ссылку на гитхаб у ботов в профиле юзера

2021-04-23 13:09 UTC, vtm9 requested changes

2021-04-23 13:09 UTC, vtm9 commented on services/app/assets/js/widgets/containers/UserProfile.jsx
> +              {stats.user.githubId && stats.user.githubName ? (
better to do just

```
stats.user.githubName
```

2021-04-23 15:21 UTC, ReDBrother approved these changes

2021-04-23 15:21 UTC, ReDBrother commented on services/app/assets/js/widgets/containers/UserProfile.jsx
> +              {stats.user.githubId && stats.user.githubName ? (
@Surtt И еще вопрос, зачем было переходить на тернарный оператор?

2021-04-23 19:16 UTC, merged

2021-04-23 19:16 UTC, ReDBrother commented
Здорово. Поздравляю с первым принятым пр ;)

2021-04-23 20:10 UTC, Surtt commented
Благодарю :)

2021-04-24 18:13 UTC, vtm9 commented
Yay