1004 task refactoring
hexlet-codebattle/codebattle pull request #1007
Opened 2021-04-24 08:20 UTC by nunsez

![github-icon](https://avatars0.githubusercontent.com/in/15368?s=40&amp;v=4) closes #1004

2021-04-24 11:49 UTC, ReDBrother commented on services/app/assets/js/widgets/slices/UIState.js
> +const UIState = createSlice({
Лучше строго по конвеции и с большой буквы начинать имена классов или jsx компонентов.
```suggestion
const gameUI = createSlice({
```

2021-04-24 11:49 UTC, ReDBrother commented on services/app/assets/js/widgets/components/Task.jsx
> +import '../../../css/taskComponent.scss';
Все импорты статики у нас происходят на самом верхнем уровне. Добавьте в style.scss импорт ваших стилей.

2021-04-24 11:49 UTC, ReDBrother commented on services/app/assets/js/widgets/App.jsx
> +  key: 'UIState',
```suggestion
const gameUIPersistConfig = {
  key: 'gameUI',
```

2021-04-24 11:49 UTC, ReDBrother commented on services/app/assets/css/taskComponent.scss
> +      background-color: #f1f1f1;
По хорошему, у нас в стилях не должны руками прописаны цвета или размеры в пикселях (Если только другого выбора нет). Принять можно, но если есть желание, то лучше сейчас отдельно выделить переменные под подобные менюшки, если уже их не задали ранее.

2021-04-24 12:49 UTC, nunsez commented on services/app/assets/css/taskComponent.scss
> +      background-color: #f1f1f1;
Да, я лучше перепишу

2021-04-25 15:26 UTC, ReDBrother requested changes

2021-04-25 15:26 UTC, ReDBrother commented on services/app/assets/js/widgets/slices/gameUI.js
> +];
Давай persistWhitelist уберем в App.jsx и можно будет принимать пр.

2021-04-26 06:26 UTC, nunsez commented on services/app/assets/js/widgets/slices/gameUI.js
> +];
Окей, Забавно, сначала сделал этот массив в App.jsx, но подумал что лучше будет следить за ним непосредственно в слайсе.
Видимо лучше всё-таки следить за ним на этапе формирования персист конфига.

2021-04-26 09:26 UTC, ReDBrother commented on services/app/assets/js/widgets/slices/gameUI.js
> +];
Ага, собственно можно было наоборот весь конфиг в слайс затащить. ;)

2021-04-26 09:26 UTC, merged

2021-04-26 09:28 UTC, ReDBrother commented
Поздравляю с первым контрибьюшеном в проект ;)))
На очень крутом уровне, серьозно.