add url hash for #lobby, #tournaments and #completedGames
hexlet-codebattle/codebattle pull request #1111
Opened 2022-06-21 06:36 UTC by avshukan

![github-icon](https://avatars0.githubusercontent.com/in/15368?s=40&amp;v=4) closes #__ISSUE_ID__
issue 1060
https://github.com/hexlet-codebattle/codebattle/issues/1060

Добавил hash-параметр в url

2022-06-21 12:49 UTC, ReDBrother requested changes

2022-06-23 06:40 UTC, avshukan commented on services/app/assets/js/widgets/containers/LobbyWidget.jsx
>            id="lobby-tab"
Добавил отдельный файл конфига

2022-06-23 06:46 UTC, avshukan commented on services/app/assets/js/widgets/containers/LobbyWidget.jsx
> +
Я посмотрел observer, но мне не хватает понимания, как его приспособить.

1. На ссылки вешаем обработчики, которые обновляют window.location.hash

2. Добавляем useEffect, который отслеживает изменение window.location.hash и по значению hash делает активными два элемента - ссылку и содержимое.

?. Я не много не догоняю, как и в какой момент изменить классы для ссылки и контента, которые должны перестать быть активными

2022-06-23 14:47 UTC, ReDBrother commented on services/app/assets/js/widgets/containers/LobbyWidget.jsx
> +
> ?. Я не много не догоняю, как и в какой момент изменить классы для ссылки и контента, которые должны перестать быть активными

По идее, наш обсервер не только должен будет следить за hash, но и формировать глобальный контекст. Это может быть как и объект, на основе которого dom элементы будут знать кто активный. Либо мы можем сформировать ref ссылки и передать их элементам. Имея на руках ref'ы всех табов, наш обсервер может манипулировать каждым элементом и указать, кто активный.

2022-06-23 14:48 UTC, merged

2022-06-23 14:48 UTC, ReDBrother commented
Поздравляю с первым принятым пуллреквестом)