Fixed issue with weak visualization of required fields
hexlet-codebattle/codebattle pull request #1454
Opened 2023-05-11 08:14 UTC by GordienkoEvgeny

visualization of required fields

Fixes #1445

2023-05-11 09:25 UTC, GordienkoEvgeny commented
Fixed incorrect location of the Save and Back buttons on the Create page 
Fixes #1443

2023-05-11 10:09 UTC, ReDBrother requested changes

2023-05-11 10:09 UTC, ReDBrother commented on services/app/apps/codebattle/assets/css/style.scss
> +  margin-bottom: 0.5rem !important;
important правила не пишем (Где сейчас это есть, это ошибка)

2023-05-12 14:55 UTC, ReDBrother approved these changes

2023-05-12 15:58 UTC, merged