Users rating list
hexlet-codebattle/codebattle pull request #1504
Opened 2023-06-18 20:01 UTC by IoannP

Fixes #1452

1) пофиксил скроллинг

ну и от себя:
1) добавил select чтобы менять размер страницы, если понравится будет супер.
2) немного поправил отступ сверху у иконки языка

2023-06-18 22:06 UTC, ReDBrother requested changes

2023-06-18 22:06 UTC, ReDBrother commented on services/app/apps/codebattle/assets/js/widgets/components/LanguageIcon.jsx
> +const LanguageIcon = ({ lang }) => <span className={cn('d-flex', iconsToClass[lang])} />;
Проблема в том, что поправлен кейс в профиле пользователя, а все остальные кейсы упали. Например: лобби -> список игр

2023-06-19 06:32 UTC, IoannP commented on services/app/apps/codebattle/assets/js/widgets/components/LanguageIcon.jsx
> +const LanguageIcon = ({ lang }) => <span className={cn('d-flex', iconsToClass[lang])} />;
Ок. Посмотрю исправлю.

2023-06-19 13:45 UTC, ReDBrother commented
Сорри, даже не так. На разных браузерах эти иконки по разному центрируются.
Когда ставили отступ, то отталкивались от Google Chrome браузера, который у нас в приоритете

2023-06-19 14:03 UTC, ReDBrother commented on services/app/apps/codebattle/assets/js/widgets/components/LanguageIcon.jsx
> +const LanguageIcon = ({ lang }) => <span className={cn('d-flex', iconsToClass[lang])} />;
Не, мой косяк. Safari плохо дружит с нашими иконками. Буд уже сам думать как обойти

2023-06-19 14:03 UTC, merged