fix bug issue 1551
hexlet-codebattle/codebattle pull request #1573
Opened 2023-08-08 08:44 UTC by GusinieIstorii

Fixes #__ISSUE_ID__1551

2023-08-08 14:30 UTC, fey commented
@GusinieIstorii добрый день, чтобы залинковать ПР с ищщусом, нужно сделать вставить в сообщение вот так номер ищщуса - `#123`

2023-08-08 15:03 UTC, GusinieIstorii commented
@fey понел, спасибо :D

2023-08-08 20:17 UTC, ReDBrother requested changes

2023-08-09 09:23 UTC, ReDBrother approved these changes

2023-08-09 09:29 UTC, merged