[#1240] fix filter tag list and improve layout of game creation modal
hexlet-codebattle/codebattle pull request #1625
Opened 2023-10-04 14:54 UTC by ushachev

Fixes #1240

  - список тегов для фильтрации задач  соответствует списку тегов задач выбранного уровня. Действующая реализация предоставляет для выбора все 5 возможных тегов, в независимости от наличия определённого тега среди задач выбранного уровня
  - изменена логика формирования списка задач, доступных для выбора в зависимости от выбранных тегов - в список попадают задачи, отмеченные ЛЮБЫМ из выбранных тегов. Действующая реализация фильтрует задачи, отмеченные КАЖДЫМ выбранным тегом
  - исправлена ошибка в коде в [строке](https://github.com/hexlet-codebattle/codebattle/blob/4a96fc10d68dfb7233bc31b187fd8fd5ee8857e1/services/app/apps/codebattle/assets/js/widgets/pages/lobby/TaskChoice.jsx#L69). Значение по умолчанию не будет присвоено при [таком вызове](https://github.com/hexlet-codebattle/codebattle/blob/4a96fc10d68dfb7233bc31b187fd8fd5ee8857e1/services/app/apps/codebattle/assets/js/widgets/pages/lobby/TaskChoice.jsx#L121), поэтому при первоначальном рендеринге когда в значении `userStats` ещё будет ` {} `, в [строке](https://github.com/hexlet-codebattle/codebattle/blob/4a96fc10d68dfb7233bc31b187fd8fd5ee8857e1/services/app/apps/codebattle/assets/js/widgets/pages/lobby/TaskChoice.jsx#L70) появится ошибка `Error reading avatarUrl of undefined`. Кроме того из всей статистики юзера используется только ссылка на аватар. Поэтому в стейте достаточно хранить только `avatarUrl` и немного упростить код
  - адаптирована модалка с созданием игры под mobile при ширине экрана от 320px
  - убраны излишне примененные bootstrap стили

Судя по #1473 логика подбора задач с каждым выбранным тегом действует и на бэкенде. Поэтому с тегами `string` и `math` находится единственная задача уровня `hard` из всех существующих и это - `livenshtein_distance` ) На мой взгляд, это нарушает идею поиска по тегам, которая в том, что выбранный тег сужает диапазон поиска, но добавление тега к выбранным - расширяет.

Скриншоты привожу для 320px и 576px - выше уже выглядит единообразно

| Было | Стало |
|:-:|:-:|
|320px|320px|
|![screencapture-localhost-4000-2023-10-04-17_09_32](https://github.com/hexlet-codebattle/codebattle/assets/37400913/fc73be91-3186-4188-bd07-073e6db70fa9)|![screencapture-localhost-4000-2023-10-04-17_42_25](https://github.com/hexlet-codebattle/codebattle/assets/37400913/b8b17496-573b-4fd4-9fb8-51b164a90649)|
|576px|576px|
|![screencapture-localhost-4000-2023-10-04-17_25_11](https://github.com/hexlet-codebattle/codebattle/assets/37400913/edb58070-6219-4bac-95ee-d64774cc0285)|![screencapture-localhost-4000-2023-10-04-16_57_38](https://github.com/hexlet-codebattle/codebattle/assets/37400913/4fcf8c96-af6d-4068-84b1-aad3b2b6736f)|

2023-10-04 16:09 UTC, ReDBrother requested changes

2023-10-04 16:12 UTC, ReDBrother commented on services/app/apps/codebattle/assets/js/widgets/pages/lobby/CreateGameDialog.jsx
> +            }}
Давай сделаем по красоте и все коллбеки выделим в отдельные функции и уже их будем передавать компонентам.

2023-10-04 16:14 UTC, ReDBrother commented on services/app/apps/codebattle/assets/js/widgets/pages/lobby/CreateGameDialog.jsx
> +            }}
И используй хук useCallback, который позволяет хранить ссылку на обработчик и не переопределять его, если данные и функции используемые им не были изменены.

2023-10-10 15:54 UTC, ReDBrother commented on services/app/apps/codebattle/assets/js/__tests__/LobbyWidget.test.jsx
> -      expect(restTag).toBeEnabled();
А почему мы снесли промежуточные проверки?

2023-10-10 16:16 UTC, ushachev commented on services/app/apps/codebattle/assets/js/__tests__/LobbyWidget.test.jsx
> -      expect(restTag).toBeEnabled();
логика фильтра по тегам изменилась. В текущей реализации выводятся все возможные теги и если в выборке задач нет задачи с определённым тегом, то его кнопка недоступна. Далее при нажатии  кнопки тега из доступных, выборка сужается по наличию нажатого тега, и, если в этой выборке нет каких-то тегов, то кнопки этих тегов тоже становятся недоступны. Именно это поведение проверялось в удалённых строчках теста. При такой логике чем больше тегов выбрано - тем меньше задач для выбора, либо вообще нет, что приводило к подбору задач другого уровня.  Это явно не соответствовало ожиданиям пользователя (#1473).
 
В предлагаемой реализации выводятся кнопки только тех тегов, которые есть у задач выбранного уровня. И все они доступны. Нажатие любой сузит выборку задач по выбранному тегу, но нажатие следующих - расширит эту суженную выборку задачами с новым тегом. То есть включение всех кнопок тегов будет равносильно невключению ни  одной, то есть для подбора доступны все задачи выбранного уровня

2023-10-10 16:37 UTC, ushachev commented
- добавлена оптимизация рендера с помощью `memo/useCallback` и выделения блоков по изменению уровня задач, выбора противника и выбора задачи. Теперь изменение любого из них не приводит к перерендеру других
- добавлено количество доступных задач в название опции `random task`. Ранее не хватало отзывчивости в интерфейсе по нажатию кнопок тегов. Цвет кнопки менялся, а что изменилось можно было понять только открыв список выбора
  <details>
    <summary>так более информативно</summary>
    

    ![Screenshot from 2023-10-10 19-32-59](https://github.com/hexlet-codebattle/codebattle/assets/37400913/d45064cc-1a0e-4171-8dc6-accf3e005c8b)
  </details>

2023-10-10 16:53 UTC, merged