add scroll to dropdown issue #1802
hexlet-codebattle/codebattle pull request #1853
Opened 2024-04-27 18:48 UTC by MaratSalakh

Fixes #1802
Add classes to Dropdown for scrolling.

2024-04-28 20:25 UTC, ReDBrother requested changes
Cуппер, останется дооформить =)

2024-04-28 20:25 UTC, ReDBrother commented on services/app/apps/codebattle/assets/css/style.scss
> +.scrollable-menu-dropdown-chat { height: auto; max-height: 400px; overflow-x: hidden; }
Мы стараемся кастомные классы задавать только по необходимости и каких нет в текущей библиотеке bootstrap

```suggestion
.cb-scrollable-menu-dropdown-chat { max-height: 400px }
```

2024-04-28 20:25 UTC, ReDBrother commented on services/app/apps/codebattle/assets/js/widgets/components/Rooms.jsx
> +        <Dropdown.Menu className="scrollable-menu-dropdown-chat">
К нашим кастомным классам делают приписку `cb` (СodeBattle)

```suggestion
        <Dropdown.Menu className="h-auto cb-overflow-x-hidden cb-scrollable-menu-dropdown-chat">
```

2024-05-01 08:47 UTC, MaratSalakh commented
спасибо за правки, сделал коммит

2024-05-01 14:31 UTC, ReDBrother approved these changes

2024-05-01 14:31 UTC, merged