Issue_#1979/Auto scroll to latest message
hexlet-codebattle/codebattle pull request #1992
Opened 2024-10-16 15:52 UTC by Titonatos

Fixes #1979

Поменял stayScrolled на scrollBottom из react-stay-scrolled

2024-10-16 20:57 UTC, ReDBrother commented
Погоди, а если мы уже проскролили чат наверх и не хотим падать вниз при каждом новом сообщении? Допустим, мы хотим почитать историю переписки, тогда нам нужно это отслеживать отдельно

2024-10-16 20:59 UTC, ReDBrother requested changes

2024-10-16 20:59 UTC, ReDBrother commented on services/app/apps/codebattle/assets/js/widgets/components/Messages.jsx
> +    scrollBottom();
Нельзя просто скролить на каждый чих, нужно учитывать что мы в этот момент можем читать историю сообщений.

2024-10-19 13:00 UTC, Titonatos commented
В таком случае это issue не актуально?
Т.к. при stayScrolled всё работает, как вы указали: если отскролить наверх, нас не уведёт к последнему сообщению.

2024-10-19 22:37 UTC, ReDBrother commented
Да, но проблема осталась, ее просто нужно решать иначе, как например делает телеграмм:
Он в окне чата дает кнопку вниз, которая автоматически скролит к последнему сообщению

2024-10-19 22:39 UTC, ReDBrother commented
<img width="352" alt="Untitled 17" src="https://github.com/user-attachments/assets/c3674bce-f12b-4c2c-84a4-0dccd77a6dca">

2025-01-25 08:16 UTC, closed without merging