update php version to 7.4.7
hexlet-codebattle/codebattle pull request #792
Opened 2020-09-13 09:42 UTC by fey

![github-icon](https://avatars0.githubusercontent.com/in/15368?s=40&amp;v=4) closes #791

2020-09-13 09:44 UTC, fey commented
Плюс микрофикс шаблона функции (чтобы по стандартам был)

2020-09-14 09:11 UTC, ReDBrother requested changes

2020-09-14 09:11 UTC, ReDBrother commented on services/app/lib/codebattle/languages.ex
> +        },
Типы прописать конечно хорошо, но они нужны, если мы можем их в сигнатуру функции прописать. Если да, то в таком случае нужно не просто добавить типы, но и переделать темплейт и часть модификаторов, чтобы генераторы кода знали, что мы работаем с языком, который предоставляет типы.

Ну и тесты переделать придется на бекенде.

2020-09-14 09:15 UTC, fey commented on services/app/lib/codebattle/languages.ex
> +        },
Сложно. Давай я ПР разделю на части, отдельно апдейт пхп, отдельно фикс кодстайла темплейта, типы в конце будут.

2020-09-14 09:16 UTC, fey commented on services/app/lib/codebattle/languages.ex
> +        },
Я просто правил темплейт, добавлял типы, тип темплейта ни типизированный менял, но потом откатывал назад и видимо косякнул.

2020-09-14 09:20 UTC, ReDBrother commented on services/app/lib/codebattle/languages.ex
> +        },
Давай, так будет легче. Если будут трудности, можем вместе засесть за остальные части.

2020-09-17 19:01 UTC, ReDBrother approved these changes

2020-09-17 19:01 UTC, merged