#889: remove TopPlayersMonthly, add TopPlayersPerPeriod, update LobbyWidget
hexlet-codebattle/codebattle pull request #891
Opened 2020-12-20 12:54 UTC by CalledByThe4ire

![github-icon](https://avatars0.githubusercontent.com/in/15368?s=40&amp;v=4) closes #__ISSUE_ID__

2020-12-20 13:57 UTC, vtm9 requested changes

2020-12-20 13:57 UTC, vtm9 commented on services/app/assets/js/widgets/components/TopPlayers/TopPlayersPerPeriod.jsx
> +        .startOf(period === periodType.MONTHLY ? 'month' : 'week')
тут похоже на костыль. лучше сделать отдельно map для periodType в 'month' and 'week'

2020-12-20 14:03 UTC, vtm9 commented
похоже надо конфликты порешать

2020-12-20 17:27 UTC, ReDBrother commented on services/app/assets/js/widgets/components/TopPlayers/TopPlayersPerPeriod.jsx
> +/* eslint-disable jsx-a11y/anchor-is-valid */
На самом деле очень хорошее правило, его не стоит игнорировать в продакшен проектах. https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md

2020-12-20 17:27 UTC, ReDBrother commented on services/app/assets/js/widgets/containers/LobbyWidget.jsx
> +            </Button>
Лучше стилизовать ссылку под кнопку, нежели делать из кнопки ссылку.

2020-12-20 17:30 UTC, CalledByThe4ire commented on services/app/assets/js/widgets/components/TopPlayers/TopPlayersPerPeriod.jsx
> +        .startOf(period === periodType.MONTHLY ? 'month' : 'week')
добавил динамическую диспетчеризацию

2020-12-20 17:38 UTC, CalledByThe4ire commented on services/app/assets/js/widgets/components/TopPlayers/TopPlayersPerPeriod.jsx
> +/* eslint-disable jsx-a11y/anchor-is-valid */
вернул

2020-12-20 17:43 UTC, CalledByThe4ire commented on services/app/assets/js/widgets/containers/LobbyWidget.jsx
> +            </Button>
поправил

2020-12-20 17:52 UTC, ReDBrother approved these changes

2020-12-20 18:01 UTC, vtm9 approved these changes

2020-12-20 18:06 UTC, merged

2020-12-20 20:09 UTC, imamatory commented on services/app/assets/js/widgets/components/TopPlayers/TopPlayersPerPeriod.jsx
> +    axios.get(`/api/v1/users?${queryParamsString}`).then(res => {
а почему запрос напрямую из компонента, редакс уже выкинули?

2020-12-20 20:09 UTC, imamatory commented on services/app/assets/js/widgets/components/TopPlayers/TopPlayersPerPeriod.jsx
> +    const queryParamsString = qs.stringify({
Параметры необязательно сериализовывать руками, axios сделает это сам если передать объект в ключ `params` вторым аргументом

2020-12-20 20:09 UTC, imamatory commented on services/app/assets/js/widgets/components/TopPlayers/TopPlayersPerPeriod.jsx
> +                      throw new Error(`Unknown period: ${periodValue.trim()}`);
Вангую, что если будет ошибка, то `undefined is not a function`, потому что скорее всего придет не неизвестный период, а undefined или какой-то другой тип, в таком случае упадет вызов trim еще до выброса исключения

2020-12-22 18:13 UTC, CalledByThe4ire commented on services/app/assets/js/widgets/components/TopPlayers/TopPlayersPerPeriod.jsx
> +    axios.get(`/api/v1/users?${queryParamsString}`).then(res => {
Вношу все твои правки, добавил `reducer`, на днях создам новый PR и попрошу тебя посмотреть