Обновил компоненты TopPlayers: TopPlayersPerPeriod и TopPlayersEver, вынес асинхронную обработку запроса в отдельный редъюсер, переписал сам запрос, изменил UI
hexlet-codebattle/codebattle pull request #903
Opened 2020-12-22 18:39 UTC by CalledByThe4ire

![github-icon](https://avatars0.githubusercontent.com/in/15368?s=40&amp;v=4) closes #__ISSUE_ID__

2020-12-22 19:59 UTC, imamatory commented on services/app/assets/js/widgets/components/TopPlayers/TopPlayersPerPeriod.jsx
> +      element.classList.add('text-black');
Почему это не через css делается?

2020-12-22 19:59 UTC, imamatory commented on services/app/assets/js/widgets/components/TopPlayers/TopPlayersPerPeriod.jsx
> +        setRating(response.payload.users);
А что поменялось принципиально? Запрос идет через экшены, данные кладуться в редакс стор, но чтение все равно из локального стейта.

2020-12-22 19:59 UTC, imamatory commented on services/app/assets/js/widgets/components/TopPlayers/TopPlayersPerPeriod.jsx
> +    };
Эти параметры описывают детали получения пользователей с сервера, а не их отображение. Кажется, что им место не в компоненте, а в action creator или чем-то таком

2020-12-22 19:59 UTC, imamatory commented on services/app/assets/js/widgets/slices/leaderboard.js
> +    [fetchUsers.pending]: (state, action) => {
Я вот такое не люблю писать на каждый запрос. Обычно у меня свои абстракции, которые из проекта в проект перетекают, но тут я недавно увидел в точности мой паттер в либе https://github.com/ava/use-http
Еще не тыкал ее, может она не очень, но идея верная. Не предлагаю тут что-то менять, но может быть будет интересно попробовать.

2020-12-22 20:00 UTC, vtm9 requested changes

2020-12-22 20:00 UTC, vtm9 commented on services/app/assets/js/widgets/slices/leaderboard.js
> +
ажется немного сложное решение @imamatory о думаешь?

2020-12-23 06:45 UTC, CalledByThe4ire commented on services/app/assets/js/widgets/components/TopPlayers/TopPlayersPerPeriod.jsx
> +        setRating(response.payload.users);
поправил

2020-12-23 06:46 UTC, CalledByThe4ire commented on services/app/assets/js/widgets/components/TopPlayers/TopPlayersPerPeriod.jsx
> +    };
убрал state, теперь всё достаю только из redux

2020-12-23 06:48 UTC, CalledByThe4ire commented on services/app/assets/js/widgets/components/TopPlayers/TopPlayersPerPeriod.jsx
> +      element.classList.add('text-black');
убрал эти обработчики

2020-12-23 06:48 UTC, CalledByThe4ire commented on services/app/assets/js/widgets/components/TopPlayers/TopPlayersPerPeriod.jsx
> +                      onMouseEnter={() => handlePeriodMouseEnter(anchorMonthRef.current)}
поправил

2020-12-23 07:30 UTC, CalledByThe4ire commented on services/app/assets/js/widgets/slices/leaderboard.js
> +    [fetchUsers.pending]: (state, action) => {
может, пояснишь в личке подробней, какую именно абстракцию ты привык использовать, мне было бы крайне полезно узнать

2020-12-23 13:14 UTC, imamatory commented on services/app/assets/js/widgets/slices/leaderboard.js
> +    [fetchUsers.pending]: (state, action) => {
Идея взята из https://github.com/Qlean/redux-struct в которой основная идея что запросы можно представлять не как код, который их выполняет, а как данные. Это хорошо ложится на реакт, в компоненте не приходится обрабатывать события, обрабатываешь только изменения данных. И вот use-http используют эту идею, только на хуках сделали. не знаю как с иммером их подружить, но я оговорился, что не юзал.

Если есть вопросы пиши в слак `imamatory`

2020-12-24 06:39 UTC, CalledByThe4ire commented on services/app/assets/js/widgets/slices/leaderboard.js
> +    [fetchUsers.pending]: (state, action) => {
спасибо большое, буду изучать! Пока тогда предлагаю принять PR в таком виде

2020-12-27 19:05 UTC, vtm9 approved these changes

2020-12-27 19:08 UTC, merged