improve game actions btns
hexlet-codebattle/codebattle pull request #952
Opened 2021-02-06 14:28 UTC by sdwayy

![github-icon](https://avatars0.githubusercontent.com/in/15368?s=40&amp;v=4) closes #949

![image](https://user-images.githubusercontent.com/46839386/107120942-b2dfce80-68a0-11eb-98b2-eb7fa805252c.png)

2021-02-10 13:50 UTC, vtm9 requested changes

2021-02-10 13:50 UTC, vtm9 commented on services/app/assets/js/widgets/components/GameActionButtons.jsx
> +    title="Check solution"
надо как-то показать текст о том, что можно Ctrl_or_CMD + Enter юзать
предлагаю в этом же тултипе

2021-02-10 13:50 UTC, vtm9 commented on services/app/assets/js/widgets/components/GameActionButtons.jsx
> +    title="Check solution"
Плюс кнопку Reset тогда для консистентности надо тоже только иконкой показывать, и только тултипом reset.

2021-02-10 13:50 UTC, vtm9 commented on services/app/assets/js/widgets/components/GameActionButtons.jsx
> +    title="Check solution"
Саму иконку check, может тоже поменять? Сейчас такое ощущение, что сейчас кнопка уже показывает успешное завершение тестов, а надо что-то типо play

2021-02-10 13:50 UTC, vtm9 commented on services/app/assets/js/widgets/components/GameActionButtons.jsx
> +    title="Check solution"
![image](https://user-images.githubusercontent.com/16337910/107518344-f3508c80-6bbf-11eb-844d-53a2bff7e0a0.png)

2021-02-10 13:50 UTC, vtm9 commented on services/app/assets/js/widgets/components/GameActionButtons.jsx
> +    title="Check solution"
![image](https://user-images.githubusercontent.com/16337910/107518414-04010280-6bc0-11eb-9e87-20a042653f47.png)
это можно на reset, и в тултипе можно написать, что просто вернуть изначальный template

2021-02-10 13:50 UTC, vtm9 commented on services/app/assets/js/widgets/components/GameActionButtons.jsx
> +    title="Check solution"
иначе не совсем понятно что за ресет

2021-02-10 14:23 UTC, ReDBrother commented on services/app/assets/js/widgets/components/GameActionButtons.jsx
> +    title="Check solution"
А может просто еще одну панель сделать, не пытаться все уместить в одну? А так да, по иконкам трудно разобраться что, зачем и почему.

2021-02-10 15:28 UTC, sdwayy commented
![image](https://user-images.githubusercontent.com/46839386/107531205-a7a4df80-6bcd-11eb-81cd-95ed23d8ae99.png)

2021-02-13 11:28 UTC, vtm9 approved these changes

2021-02-13 11:29 UTC, merged