remove warning from tests frontend
hexlet-codebattle/codebattle pull request #996
Opened 2021-04-10 09:11 UTC by possesion

![github-icon](https://avatars0.githubusercontent.com/in/15368?s=40&amp;v=4) closes #__ISSUE_ID__
Пофиксил имеющиеся тесты, чтобы не вылезало каждый раз полотно при вызове testing library.

2021-04-10 15:48 UTC, ReDBrother requested changes

2021-04-10 15:48 UTC, ReDBrother commented on services/app/assets/js/widgets/slices/usersInfo.js
> +      if (user && user.id) state[user.id] = user;
Так стоп, это не вариант. Нельзя ломать обработчик, даже ради тестов. Нужно смотреть где задаётся пользователь, раз в тестах всё падает.

2021-04-10 17:18 UTC, possesion commented on services/app/assets/js/widgets/slices/usersInfo.js
> +      if (user && user.id) state[user.id] = user;
ок, я посмотрю, где он вызывается. Тест не падает, выпадает предупреждение, что присутствует кейс в котором идет обращение к ключу 'id' объекта юзер, значение которого undefined.

2021-05-09 21:18 UTC, vtm9 commented on services/app/assets/js/widgets/slices/usersInfo.js
> +      if (user && user.id) state[user.id] = user;
я думаю костыль уместен)

2021-05-09 21:18 UTC, vtm9 commented on services/app/assets/js/widgets/slices/usersInfo.js
> +      if (user && user.id) state[user.id] = user;
@ReDBrother , или чтоит что-то переделать?

2021-05-10 22:16 UTC, ReDBrother commented on services/app/assets/js/widgets/slices/usersInfo.js
> +      if (user && user.id) state[user.id] = user;
Я не помню, но вроде в чате кодбатла уже придумали до меня как решить этот вопрос.
Мы кажется мы уже перешли черту, когда костыли были уместны)))

2021-05-23 17:14 UTC, possesion commented
много воды утекло. Дописал тесты на User settings, убрал костыль прогнал все тесты на фронте. Не падает

2021-05-23 21:01 UTC, possesion commented
пофиксил прошлые ошибки и дописал пару тестов на UserSettings. Можно туда еще, что нибудь добавить при желании.

2021-05-24 00:31 UTC, merged